[default_session]
startup_command = "nvim -c ':lua Snacks.picker.files()'"
preview_command = "lsd --blocks=size --blocks=date --blocks=name --icon=always --color=always {}"

[[session]]
name = "tmux_config"
path = "~/dotfiles/tmux/.tmux.conf"
startup_command = "nvim .tmux.conf"
preview_command = "bat --color=always ~/dotfiles/tmux/.tmux.conf"

[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "nvim -c ':lua Snacks.picker.files({hidden = true})'"
