notARepository: 'quit'
git:
  # See https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md
  # Setup with difftastic
  paging:
    colorArg: always
    pager: ""
    # If true, Lazygit will use whatever pager is specified in `$GIT_PAGER`, `$PAGER`, or your *git config*. If the pager ends with something like ` | less` we will strip that part out, because less doesn't play nice with our rendering approach. If the custom pager uses less under the hood, that will also break rendering (hence the `--paging=never` flag for the `delta` pager).
    useConfig: false
    # pick diff tool based on environment variable
    externalDiffCommand: >
      sh -c '
        OLD_FILE="$2";
        NEW_FILE="$1";
        if [ "$LAZYGIT_DIFF_TOOL" = "difftastic" ]; then
          difft --color=always "$OLD_FILE" "$NEW_FILE";
        else
          git diff --no-ext-diff --no-index --color=always "$OLD_FILE" "$NEW_FILE" | delta --dark --paging=never;
        fi
      ' _ "$@"
os:
  editPreset: nvim
gui:
  # Catppuccin theme
  theme:
    activeBorderColor:
      - '#89b4fa'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#89b4fa'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'

  authorColors:
    '*': '#b4befe'

  showBottomLine: false
  border: rounded
  nerdFontsVersion: '3'
